#kubectl get pv #this shows actual uses of a persistent volume instance
#kubectl get pvc #this shows the 'advertisement' of all available claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
